export interface BibleBook {
  name: string;
  chapters: number;
  testament: 'Velho' | 'Novo';
  isDeuterocanonical?: boolean;
  bollsId: number;
}

export const bibleBooks: BibleBook[] = [
  // Antigo Testamento
  { name: "Gênesis", chapters: 50, testament: 'Velho', bollsId: 1 },
  { name: "Êxodo", chapters: 40, testament: 'Velho', bollsId: 2 },
  { name: "Levítico", chapters: 27, testament: 'Velho', bollsId: 3 },
  { name: "Números", chapters: 36, testament: 'Velho', bollsId: 4 },
  { name: "Deuteronômio", chapters: 34, testament: 'Velho', bollsId: 5 },
  { name: "Josué", chapters: 24, testament: 'Velho', bollsId: 6 },
  { name: "Juízes", chapters: 21, testament: 'Velho', bollsId: 7 },
  { name: "Rute", chapters: 4, testament: 'Velho', bollsId: 8 },
  { name: "1 Samuel", chapters: 31, testament: 'Velho', bollsId: 9 },
  { name: "2 Samuel", chapters: 24, testament: 'Velho', bollsId: 10 },
  { name: "1 Reis", chapters: 22, testament: 'Velho', bollsId: 11 },
  { name: "2 Reis", chapters: 25, testament: 'Velho', bollsId: 12 },
  { name: "1 Crônicas", chapters: 29, testament: 'Velho', bollsId: 13 },
  { name: "2 Crônicas", chapters: 36, testament: 'Velho', bollsId: 14 },
  { name: "Esdras", chapters: 10, testament: 'Velho', bollsId: 15 },
  { name: "Neemias", chapters: 13, testament: 'Velho', bollsId: 16 },
  { name: "Ester", chapters: 10, testament: 'Velho', bollsId: 17 },
  { name: "Jó", chapters: 42, testament: 'Velho', bollsId: 18 },
  { name: "Salmos", chapters: 150, testament: 'Velho', bollsId: 19 },
  { name: "Provérbios", chapters: 31, testament: 'Velho', bollsId: 20 },
  { name: "Eclesiastes", chapters: 12, testament: 'Velho', bollsId: 21 },
  { name: "Cânticos", chapters: 8, testament: 'Velho', bollsId: 22 },
  { name: "Isaías", chapters: 66, testament: 'Velho', bollsId: 23 },
  { name: "Jeremias", chapters: 52, testament: 'Velho', bollsId: 24 },
  { name: "Lamentações", chapters: 5, testament: 'Velho', bollsId: 25 },
  { name: "Ezequiel", chapters: 48, testament: 'Velho', bollsId: 26 },
  { name: "Daniel", chapters: 12, testament: 'Velho', bollsId: 27 },
  { name: "Oseias", chapters: 14, testament: 'Velho', bollsId: 28 },
  { name: "Joel", chapters: 3, testament: 'Velho', bollsId: 29 },
  { name: "Amós", chapters: 9, testament: 'Velho', bollsId: 30 },
  { name: "Obadias", chapters: 1, testament: 'Velho', bollsId: 31 },
  { name: "Jonas", chapters: 4, testament: 'Velho', bollsId: 32 },
  { name: "Miqueias", chapters: 7, testament: 'Velho', bollsId: 33 },
  { name: "Naum", chapters: 3, testament: 'Velho', bollsId: 34 },
  { name: "Habacuque", chapters: 3, testament: 'Velho', bollsId: 35 },
  { name: "Sofonias", chapters: 3, testament: 'Velho', bollsId: 36 },
  { name: "Ageu", chapters: 2, testament: 'Velho', bollsId: 37 },
  { name: "Zacarias", chapters: 14, testament: 'Velho', bollsId: 38 },
  { name: "Malaquias", chapters: 4, testament: 'Velho', bollsId: 39 },

  // Novo Testamento
  { name: "Mateus", chapters: 28, testament: 'Novo', bollsId: 40 },
  { name: "Marcos", chapters: 16, testament: 'Novo', bollsId: 41 },
  { name: "Lucas", chapters: 24, testament: 'Novo', bollsId: 42 },
  { name: "João", chapters: 21, testament: 'Novo', bollsId: 43 },
  { name: "Atos", chapters: 28, testament: 'Novo', bollsId: 44 },
  { name: "Romanos", chapters: 16, testament: 'Novo', bollsId: 45 },
  { name: "1 Coríntios", chapters: 16, testament: 'Novo', bollsId: 46 },
  { name: "2 Coríntios", chapters: 13, testament: 'Novo', bollsId: 47 },
  { name: "Gálatas", chapters: 6, testament: 'Novo', bollsId: 48 },
  { name: "Efésios", chapters: 6, testament: 'Novo', bollsId: 49 },
  { name: "Filipenses", chapters: 4, testament: 'Novo', bollsId: 50 },
  { name: "Colossenses", chapters: 4, testament: 'Novo', bollsId: 51 },
  { name: "1 Tessalonicenses", chapters: 5, testament: 'Novo', bollsId: 52 },
  { name: "2 Tessalonicenses", chapters: 3, testament: 'Novo', bollsId: 53 },
  { name: "1 Timóteo", chapters: 6, testament: 'Novo', bollsId: 54 },
  { name: "2 Timóteo", chapters: 4, testament: 'Novo', bollsId: 55 },
  { name: "Tito", chapters: 3, testament: 'Novo', bollsId: 56 },
  { name: "Filemon", chapters: 1, testament: 'Novo', bollsId: 57 },
  { name: "Hebreus", chapters: 13, testament: 'Novo', bollsId: 58 },
  { name: "Tiago", chapters: 5, testament: 'Novo', bollsId: 59 },
  { name: "1 Pedro", chapters: 5, testament: 'Novo', bollsId: 60 },
  { name: "2 Pedro", chapters: 3, testament: 'Novo', bollsId: 61 },
  { name: "1 João", chapters: 5, testament: 'Novo', bollsId: 62 },
  { name: "2 João", chapters: 1, testament: 'Novo', bollsId: 63 },
  { name: "3 João", chapters: 1, testament: 'Novo', bollsId: 64 },
  { name: "Judas", chapters: 1, testament: 'Novo', bollsId: 65 },
  { name: "Apocalipse", chapters: 22, testament: 'Novo', bollsId: 66 },
];
